apiVersion: apps/v1
kind: Deployment
metadata:
  name: tti301-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classificacao
  template:
    metadata:
      labels:
        app: classificacao
    spec:
      containers:
        - name: classificacao
          image: matheusap2/classificacao
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: classificacao-service
spec:
  selector:
    app: classificacao
  type: ClusterIP
  ports:
    - name: classificacao
      protocol: TCP
      port: 7000
      targetPort: 7000