apiVersion: apps/v1
kind: Deployment
metadata:
  name: tti301-logs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
        - name: logs
          image: matheusap2/logs
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: logs-service
spec:
  selector:
    app: logs
  type: ClusterIP
  ports:
    - name: logs
      protocol: TCP
      port: 8000
      targetPort: 8000